### ISSUE TITLE
To set Circle CI

### ISSUE THREAD

**Issue by orogersilva** [orogersilva/coma-bem-android#2]
To set Circle CI with standard config.

**Comment by Morbix** [comment]
I'm using (and I recommend) [Bitrise.io](https://www.bitrise.io).

**Comment by orogersilva** [comment]
I liked the way the pipeline is built (visually). Possible complex workflows via pipeline as code. And the several third party integrations. I will try with this same project. Good tip. Thanks.

**Comment by orogersilva** [comment]
As CI as a service, will be used Bitrise.io.
